language: cpp

sudo: false
dist: xenial

cache:
  apt: true
  pip: true

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
    packages:
      - gcc-8
      - g++-8
      - clang-7

env:
  matrix:
    - WITH_PNG=0
    - WITH_PNG=1
  global:
    - CXXFLAGS="-std=c++11 -Wall -Wextra -Wshadow -Werror"

before_install:
  - echo "CC=${CC} CXX=${CXX}"
  - if [ ${CC} == "gcc" ]; then
      export CC=gcc-8;
      export CXX=g++-8;
    elif [ ${CC} == "clang" ]; then
      export CC=clang-7;
      export CXX=clang++;
    fi
  - echo "CC=${CC} CXX=${CXX}"

install:
  - if [ $WITH_PNG -eq 1 ]; then
      git clone --depth 50 https://github.com/pngwriter/pngwriter.git &&
      mkdir pngwriter/build &&
      cd pngwriter/build &&
      cmake -DCMAKE_INSTALL_PREFIX=/usr .. &&
      make &&
      sudo make install;
    fi

script:
  - mkdir $TRAVIS_BUILD_DIR/build
  - cd $TRAVIS_BUILD_DIR/build
  - cmake ..
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make test
  - sudo make install
