language: cpp

sudo: false
dist: trusty

compiler:
  - gcc
  - clang

cache:
  apt: true
  pip: true

env:
  matrix:
    - WITH_PNG=0
    - WITH_PNG=1
  global:
    - CXXFLAGS="-std=c++11 -Wall -Wextra -Wshadow -Werror"

install:
  - if [ $WITH_PNG -eq 1 ]; then
      git clone --depth 50 https://github.com/pngwriter/pngwriter.git &&
      mkdir pngwriter/build &&
      cd pngwriter/build &&
      cmake -DCMAKE_INSTALL_PREFIX=/usr .. &&
      make &&
      sudo make install;
    fi

script:
  - mkdir $TRAVIS_BUILD_DIR/build
  - cd $TRAVIS_BUILD_DIR/build
  - cmake ..
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make test
  - sudo make install
